# Generated by Django 5.1.3 on 2024-12-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_cvv",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="card_expiry",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="card_number",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash on Delivery"), ("card", "Credit/Debit Card")],
                default="Unknown",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
