# Generated by Django 5.1.3 on 2024-12-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_unit_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Per Kilogram"),
                    ("item", "Per Item"),
                    ("liter", "Per Liter"),
                ],
                default="kg",
                max_length=10,
            ),
        ),
    ]
