# Generated by Django 5.1.3 on 2024-11-29 15:14

import EcoHub.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[EcoHub.accounts.validators.validate_bulgarian_phone],
            ),
        ),
    ]
