# Generated by Django 5.1.3 on 2024-11-29 15:46

import EcoHub.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[EcoHub.accounts.validators.validate_bulgarian_phone],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with this username already exists."},
                max_length=15,
                unique=True,
                validators=[EcoHub.accounts.validators.validate_username_length],
            ),
        ),
    ]
